### PR TITLE
Introduce query_string_fields filter

### PR DESCRIPTION
**Pull request by szepeviktor**
@colinleroy What do you think?

### CODE REVIEW

**Comment by colinleroy** [comment]
Seems good ! will this work though if the cache is in mu-plugins? filters from other plugins/themes may not be installed already?

**Comment by szepeviktor** [comment]
> will this work

Yes. This is a decent plugin: it starts at `init` time.

**Comment by colinleroy** [comment]
Great! Do you want me to update my PR with this one?

**Comment by szepeviktor** [comment]
No. Both filters and constants are sub-optimal.

**Comment by colinleroy** [comment]
OK ! Thanks a lot for your help, and your plugin :)

**Pull request closed without merging**
